### PR TITLE
allow puppet/systemd 7.x

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
I suspect that the CI bundler failure is unrelated to changes in this PR.

**Comment by jcpunk** [comment]
Is this something you'd like to get up on the forge ASAP or was it a sanity check sorta thing?

**Comment by jhoblitt** [comment]
I need to update a module with a dep on systemd >= 7.  This mod is one of the blockers on that update.

**Comment by jcpunk** [comment]
Published update

**Pull request merged**
